default_parameters: &default_parameters
    d_z: 2
    kernel: 'norm_fixed_var_w_skip'
    n_hidden: 512

default_theta_lr: &default_theta_lr
    lr: 1e-4

experiment:
    n_reruns: 10
    n_updates: 15000
    name: 'default'
    compute_metrics: False
    use_jit: True

pvi:
    algorithm: 'pvi'
    model: 
        use_particles: True
        n_particles: 100
        <<: *default_parameters
    theta_opt:
        <<: *default_theta_lr
        optimizer: 'rmsprop'
        lr_decay: False
        regularization: 1e-8
        clip: False
    r_opt:
        lr: 1e-2
        regularization: 1e-8
    r_precon:
        type: 'rms'
        max_norm: 1.
        agg: 'mean'
    extra_alg:
        mc_n_samples: 250

wgf_gmm:
    algorithm: 'wgf_gmm'
    model: 
        use_particles: True
        n_particles: 100
        n_components: 100
        <<: *default_parameters
    theta_opt:
        <<: *default_theta_lr
        optimizer: 'rmsprop'
        lr_decay: False
        regularization: 1e-8
        clip: False
    r_opt:
        lr: 1e-2
        regularization: 1e-8
    r_precon:
        type: 'rms'
        max_norm: 1.
        agg: 'mean'
    wgf_gmm_params:
        lambda_reg: 0.1      # Wasserstein regularization
        lr_mean: 0.01        # Learning rate for means  
        lr_cov: 0.001        # Learning rate for covariances
        lr_weight: 0.01      # Learning rate for weights
    extra_alg:
        mc_n_samples: 250

enhanced_wgf_gmm:
    algorithm: 'enhanced_wgf_gmm'
    model: 
        use_particles: True
        n_particles: 100
        n_components: 100
        <<: *default_parameters
    theta_opt:
        <<: *default_theta_lr
        optimizer: 'rmsprop'
        lr_decay: False
        regularization: 1e-8
        clip: False
    r_opt:
        lr: 1e-2
        regularization: 1e-8
    r_precon:
        type: 'rms'
        max_norm: 1.
        agg: 'mean'
    wgf_gmm_params:
        lambda_reg: 0.1      # Enhanced version parameters
        lr_mean: 0.01        # More conservative for enhanced
        lr_cov: 0.001        
        lr_weight: 0.01      
    extra_alg:
        mc_n_samples: 250

svi:
    algorithm: 'svi'
    model:
        use_particles: False
        <<: *default_parameters
    dual:
        n_hidden: 512
    theta_opt:
        <<: *default_theta_lr
        optimizer: 'rmsprop'
        lr_decay: False
        regularization: 1e-8
        clip: False
    extra_alg:

uvi:
    algorithm: 'uvi'
    model:
        use_particles: False
        <<: *default_parameters
    theta_opt:
        <<: *default_theta_lr
        optimizer: 'rmsprop'
        lr_decay: False
        regularization: 1e-8
        clip: False
    extra_alg:

sm:
    algorithm: 'sm'
    model:
        use_particles: False
        <<: *default_parameters
    theta_opt:
        <<: *default_theta_lr
        optimizer: 'rmsprop'
        lr_decay: True
        min_lr: 1e-5
        regularization: 1e-8
        clip: False
    dual:
        n_hidden: 512
    dual_opt:
        lr: 1e-3
        min_lr: 1e-5
        regularization: 1e-8
        optimizer: 'rmsprop'
        lr_decay: True
        clip: False
    extra_alg: